apiVersion: v1
kind: Secret
metadata:
  name: ai-doc-analyzer-secrets
  namespace: default
type: Opaque
stringData:
  V1_API_KEY: ""
  AI_GUARD_ENDPOINT: "https://api.au.xdr.trendmicro.com/v3.0/aiSecurity/applyGuardrails"
  AI_GUARD_APP_NAME: "ai-doc-analyzer"
  AWS_PROFILE: "umatrenddemo"
